//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web4dotnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luat
    {
        public int Id { get; set; }
        public string Chuong { get; set; }
        public string NDChuong { get; set; }
        public string Muc { get; set; }
        public string NDMuc { get; set; }
        public string Dieu { get; set; }
        public string NDDieu { get; set; }
        public string Khoan { get; set; }
        public string NDKhoan { get; set; }
    }
}
